using JetBrains.Annotations;

namespace BattleTechInfoExporter.Models;

/// <summary>
///     The performance summary of the mech lab and mech bay: the ratings of the stat bars and the numbers behind
///     them. Only working components count.
/// </summary>
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
internal sealed record MechStats(
    StatRatings Ratings,
    MovementStats Movement,
    HeatStats Heat,
    FirepowerStats Firepower,
    RangeStats Range,
    DurabilityStats Durability,
    MeleeStats Melee);

/// <summary>The stat bars, each rated up to 10 against the game's stock mechs.</summary>
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
internal sealed record StatRatings(
    int Firepower,
    int Movement,
    int Range,
    int HeatEfficiency,
    int Durability,
    int Melee);

/// <summary>The distances in meters.</summary>
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
internal sealed record MovementStats(float Walk, float Sprint, float Jump);

/// <param name="Dissipation">The heat removed per round by the built-in and mounted heat sinks.</param>
/// <param name="AlphaStrike">The heat generated by firing every weapon at once.</param>
/// <param name="AverageJump">The heat generated by an average jump.</param>
/// <param name="Shutdown">The heat at which the mech shuts down.</param>
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
internal sealed record HeatStats(float Dissipation, float AlphaStrike, float AverageJump, float Shutdown);

/// <summary>The damage of firing every weapon at once.</summary>
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
internal sealed record FirepowerStats(float Damage, float StabilityDamage);

/// <param name="Max">The longest maximum range of the weapons, in meters.</param>
/// <param name="Optimal">The weapons' average medium range, in meters.</param>
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
internal sealed record RangeStats(float Max, float Optimal);

/// <param name="Armor">The armor left on all locations.</param>
/// <param name="Structure">The structure left on all locations.</param>
/// <param name="DeathFromAboveSelfDamage">The damage the mech takes from its own jump attack.</param>
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
internal sealed record DurabilityStats(float Armor, float Structure, float DeathFromAboveSelfDamage);

/// <param name="DeathFromAboveDamage">The damage of a jump attack onto a target.</param>
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
internal sealed record MeleeStats(float Damage, float StabilityDamage, float DeathFromAboveDamage);
